### ISSUE TITLE
Potential issues with the ground truth for Zurich Lumbar data

### ISSUE THREAD

**Issue by rohanbanerjee** [sct-pipeline/fmri-segmentation#13]
Hello,
I am opening this issue so that we can have a discussion around the ground truths we have for the Zurich Lumbar data. This is a rest dataset which has 13 subjects. 

### Explanation
I have trained a 2D-UNet nnUNet with all the manually labeled dataset with all the manually labeled datasets. When I ran the inference, I observe that most of the images which have a low dice score are from the Zurich Lumbar dataset. I probed into the images and found that the some of the segmentation masks might not be the most optimal in my opinion and I would love to discuss this. For example,

(Yellow = ground truth, Red = prediction mask)

Subject - Zurich Lumbar C01
Dice: 0.5604
Slice 14
<p>
<img width="200" alt="Screen Shot 2023-06-20 at 3 44 04 PM" src="https://github.com/sct-pipeline/fmri-segmentation/assets/25586344/e705840b-9e7b-4ce7-8471-aaf5fb643918">
<img width="200" alt="Screen Shot 2023-06-20 at 3 44 45 PM" src="https://github.com/sct-pipeline/fmri-segmentation/assets/25586344/e6eb2426-cbe0-4833-870d-ab2dd80008f6">
<img width="200" alt="Screen Shot 2023-06-20 at 3 46 23 PM" src="https://github.com/sct-pipeline/fmri-segmentation/assets/25586344/0c166b19-c23c-477b-aab8-9e575572c5f9">
</p>

Slice 8
<p>
<img width="200" alt="Screen Shot 2023-06-20 at 3 51 53 PM" src="https://github.com/sct-pipeline/fmri-segmentation/assets/25586344/5043c94e-c727-4330-a4f0-3c79365f740b">
<img width="200" alt="Screen Shot 2023-06-20 at 3 53 11 PM" src="https://github.com/sct-pipeline/fmri-segmentation/assets/25586344/cb370b55-34bc-4fba-93cf-355224946dda">
<img width="200" alt="Screen Shot 2023-06-20 at 3 54 05 PM" src="https://github.com/sct-pipeline/fmri-segmentation/assets/25586344/5b6b75e4-5a3f-4f19-90df-1336c75ba23e"><br>
(The model did not predict a segmentation mask for this slice)
</p>

Subject - Zurich Lumbar C12
Dice: 0.7843

Slice 5
<p>
<img width="200" alt="Screen Shot 2023-06-20 at 4 03 25 PM" src="https://github.com/sct-pipeline/fmri-segmentation/assets/25586344/804426bc-2397-46c2-8e16-cbef5d871b1d">
<img width="200" alt="Screen Shot 2023-06-20 at 4 04 19 PM" src="https://github.com/sct-pipeline/fmri-segmentation/assets/25586344/cf56dd8e-4f7a-402c-81fc-6702c9f7e241">
<img width="200" alt="Screen Shot 2023-06-20 at 4 04 46 PM" src="https://github.com/sct-pipeline/fmri-segmentation/assets/25586344/ee6f5594-d5ce-40aa-9e7e-22cc7b008734">

Thanks!

**Comment by MerveKaptan** [comment]
Hi @rohanbanerjee, 

I wanted to check these one by one in FSLeyes. However, I just looked at the first one and I am a bit confused- am I looking at the incorrect dataset or are the subject numbers and labels mixed?
![image](https://github.com/sct-pipeline/fmri-segmentation/assets/46893456/8e3ca3ea-05f9-4945-a59b-3c3174eb72ca)
This is subject 13 slice 14 (in fsleyes, so starting from 0) for me. I also looked at slice 13 of fsleyes but this still does not seem to be the identical with the slice that you added ?? Please let me know if I am looking at the incorrect dataset/subject/slice etc! 

Thank you!!

**Comment by jcohenadad** [comment]
assuming the data showed in https://github.com/sct-pipeline/fmri-segmentation/issues/13#issue-1766081250 are
correct (referring to Merve’s answer above), I agree the ground truth segmentations are questionable

**Comment by rohanbanerjee** [comment]
Hello @MerveKaptan , sorry for the confusion, the first subject is Zurich Lumbar C01 and not C13. I hav edited the above main comment accordingly.

**Comment by MerveKaptan** [comment]
Dear all,

Thank you so much for the clarification @rohanbanerjee! 
I notice that CSF/cord contrast is very low- possibly this is because, these are lumbar data, right @jcohenadad ?

For subject C01, slice 14, I actually do not see a problem with the mask, I would draw it quite similarly I assume! What do you think is problematic?
![image](https://github.com/sct-pipeline/fmri-segmentation/assets/46893456/3e5ceef2-c4b4-4ce5-8a88-86bd8a952d04)

I think, for slice 8, I would draw the mask a bit wider, please see below (blue: original, red voxels my addition to the original)
![image](https://github.com/sct-pipeline/fmri-segmentation/assets/46893456/53b77f11-9626-40d6-88b2-287e286e3159)

I would personally draw the mask a bit bigger for slice 5 C12 as well.

Would you agree or how would you alter the mask? It seems as if this is almost a bit of a personal taste :) How can we assess this?

**Comment by kennethaweberii** [comment]
Thanks for raising this issue @rohanbanerjee.

In general, we will need to find a consistent way to approach QC for the manual segmentations. I would tend to accept the ground truth as is versus modifying it. Overall, I do not feel the ground truth for C01 and C12 is too far off and is within reason.

Due to the cauda equina, the spinal cord (and surrounding neural tissue) at the lumbosacral segments can look quite different than the cervical and thoracic segments. The boundaries between the cord and peripheral nerves is often hard to discern given the lower spatial resolution and lower contrast/signal in the functional images. Also, I expect the model will not perform as well on the lumbosacral cord given that we have fewer lumbar spinal cord fMRI datasets (unless we account for this imbalance in the training).

At this time, I think we can table this issue until we have a model trained on the full, more diverse dataset.

Below is an example from the PAM50 template where the peripheral nerves cause a pretty significant change in the appearance of the spinal cord and surrounding neural tissues:

![image](https://github.com/sct-pipeline/fmri-segmentation/assets/29933576/12a31459-a387-4bdd-92a9-d6595c901f8e)

![image](https://github.com/sct-pipeline/fmri-segmentation/assets/29933576/404bbfee-3c7e-4360-9275-39fde4fa69c1)

**Comment by jcohenadad** [comment]
My suggestion is to revisit the GT for this dataset and not include it in the model for now.
